# Generated by Django 4.0.4 on 2023-05-27 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cla_id', models.IntegerField(auto_created=True, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.IntegerField(auto_created=True, max_length=16, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.IntegerField(auto_created=True, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('t_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='c_tea', to='DrfApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(auto_created=True, max_length=16, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=32, verbose_name='名字')),
                ('s_cla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cla_stu', to='DrfApp.class')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='c_stu',
            field=models.ManyToManyField(related_name='s_course', to='DrfApp.student'),
        ),
    ]
